"""add_user_auth_fields

Revision ID: c0a1b2c3d4e5
Revises: f2c1b3a4d5e6
Create Date: 2026-03-27 09:55:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0a1b2c3d4e5"
down_revision: str | None = "f2c1b3a4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("role", sa.String(length=20), server_default="user", nullable=False)
    )
    # Add a DB-level CHECK constraint to keep schema in sync with the model
    op.create_check_constraint(
        "valid_role", "users", "role IN ('user','admin')"
    )
    op.add_column(
        "users",
        sa.Column("admin_access_granted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "users", sa.Column("admin_access_granted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "admin_access_granted_at")
    op.drop_column("users", "admin_access_granted")
    # Remove the DB-level CHECK constraint before dropping the column
    op.drop_constraint("valid_role", "users", type_="check")
    op.drop_column("users", "role")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
