"""Phase 1: Add User and APIKey tables

Revision ID: e163c3063cf1
Revises:
Create Date: 2026-03-12 14:41:41.397071

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e163c3063cf1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hint', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_is_live'), 'api_keys', ['is_live'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('education_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('daily_goal_cards', sa.Integer(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_timezone'), 'users', ['timezone'], unique=False)
    # Enforce referential integrity: api_keys.user_id -> users.id
    op.create_foreign_key(
        'fk_api_keys_user_id_users',
        'api_keys',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key first to avoid dependency issues
    op.drop_constraint('fk_api_keys_user_id_users', 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_live'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_timezone'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
